# Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

COPY ./Kafka_First_Aproach.Webapi/ ./src/Kafka_First_Aproach.Webapi/
COPY ./Kafka_First_Aproach.Contracts/ ./src/Kafka_First_Aproach.Contracts/
WORKDIR /src
RUN dotnet restore ./Kafka_First_Aproach.Webapi/ ./Kafka_First_Aproach.Contracts/

RUN dotnet publish ./Kafka_First_Aproach.Webapi/Kafka_First_Aproach.Webapi.csproj -c Release -o /app

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 13000
ENTRYPOINT ["dotnet", "webapi.dll"]

