# Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

COPY ./Kafka_First_Aproach.Consumer/ ./src/Kafka_First_Aproach.Consumer/
COPY ./Kafka_First_Aproach.Contracts/ ./src/Kafka_First_Aproach.Contracts/
WORKDIR /src
RUN dotnet restore ./Kafka_First_Aproach.Consumer/ ./Kafka_First_Aproach.Contracts/

RUN dotnet publish ./Kafka_First_Aproach.Consumer/Kafka_First_Aproach.Consumer.csproj -c Release -o /app

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "consumer.dll"]

