<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Kafka_Users_Consumer-ff809cea-4d75-46a6-a78a-3ffc380e22d7</UserSecretsId>
    <AssemblyName>consumer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.14.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kafka_First_Aproach.Contracts\Kafka_First_Aproach.Contracts.csproj" />
  </ItemGroup>
</Project>
