name: BuildNTest

on:
    workflow_call:
concurrency: 
  group: ${{github.actor_id}}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnetv: [10.0.x, 9.0.x, 8.0.x]
        
    runs-on: ${{matrix.os}}
    steps:
      - name: CheckOut_Repo
        uses: actions/checkout@v4

      - name: SetUp_Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{matrix.dotnetv}}

      - name: Restore_Dep 
        run: dotnet restore

      - name: Build_Projects
        run: dotnet build

      - name: Run_Unit_Tests
        run: dotnet test
